### PR TITLE
feat: add control to constrain dragging to viewport

### PR DESCRIPTION
**Pull request by mmissey**
Adds an option to constrict dragging within the viewport.

This constricts on the mouse/touch client position, but it'd be possible to do so on the dragging element if we had access to the width/height.

Fixes: https://github.com/idanen/react-draggable/issues/1

### CODE REVIEW

**Comment by idanen** [comment]
Thanks for taking the time and effort to contribute.

The actual intent was to limit where can the target element be dragged to. 
We have `targetRef` which is the dragged target, and we can `getBoundingClientRect()` on it to check if it reached the bounds.
We should only calculate the rect when dragging starts (and not while dragging) to avoid jank

**Comment by mmissey** [comment]
@idanen I made the change but there are some new issues:
1. Calculating only on start drag means that scroll bars or changes in viewport size will mess with the available space. ie: if you start to drag when there is a scroll bar and then it goes away, the calculated viewport limits are no longer correct.

2. If there is any animation on the draggable object that changes the dimensions, it could potentially be incorrect

**Comment by idanen** [comment]
Your points make me think maybe we should make no assumptions regarding the limiting rect.
Instead of the `viewport` as input, we can receive the actual rect values and maybe default to `window.innerWidth` `window.innerHeight`.
Makes sense?

**Comment by idanen** [comment]
Now added Karma so we'd be able to write proper tests for this (bounding rect changes while dragging, which JSDOM can't cover)

**Comment by idanen** [comment]
This received higher priority for us, so pushed the feature on the master branch

**Pull request closed without merging**
